
// Statik hududlar — backendga bog'liq emas
const VILOYATLAR = [
  {
    id: 1, nomi: 'Toshkent shahri',
    hududlar: [
      { id: 1,  nomi: 'Bektemir tumani' },
      { id: 2,  nomi: 'Chilonzor tumani' },
      { id: 3,  nomi: 'Hamza tumani' },
      { id: 4,  nomi: 'Mirobod tumani' },
      { id: 5,  nomi: 'Mirzo Ulug\'bek tumani' },
      { id: 6,  nomi: 'Ohangaron tumani' },
      { id: 7,  nomi: 'Olmazor tumani' },
      { id: 8,  nomi: 'Sergeli tumani' },
      { id: 9,  nomi: 'Shayxontohur tumani' },
      { id: 10, nomi: 'Uchtepa tumani' },
      { id: 11, nomi: 'Yakkasaroy tumani' },
      { id: 12, nomi: 'Yunusobod tumani' },
      { id: 13, nomi: 'Yashnobod tumani' },
    ],
  },
  {
    id: 2, nomi: 'Toshkent viloyati',
    hududlar: [
      { id: 14, nomi: 'Angren shahri' },
      { id: 15, nomi: 'Bekabad tumani' },
      { id: 16, nomi: 'Bo\'ka tumani' },
      { id: 17, nomi: 'Bo\'stonliq tumani' },
      { id: 18, nomi: 'Chinoz tumani' },
      { id: 19, nomi: 'Chirchiq shahri' },
      { id: 20, nomi: 'Qibray tumani' },
      { id: 21, nomi: 'Ohangaron tumani' },
      { id: 22, nomi: 'Oqqo\'rg\'on tumani' },
      { id: 23, nomi: 'Parkent tumani' },
      { id: 24, nomi: 'Piskent tumani' },
      { id: 25, nomi: 'Quyi Chirchiq tumani' },
      { id: 26, nomi: 'Yuqori Chirchiq tumani' },
      { id: 27, nomi: 'Zangiota tumani' },
    ],
  },
  {
    id: 3, nomi: 'Samarqand viloyati',
    hududlar: [
      { id: 28, nomi: 'Samarqand shahri' },
      { id: 29, nomi: 'Bulung\'ur tumani' },
      { id: 30, nomi: 'Ishtixon tumani' },
      { id: 31, nomi: 'Jomboy tumani' },
      { id: 32, nomi: 'Kattaqo\'rg\'on tumani' },
      { id: 33, nomi: 'Narpay tumani' },
      { id: 34, nomi: 'Nurobod tumani' },
      { id: 35, nomi: 'Oqdaryo tumani' },
      { id: 36, nomi: 'Pastdarg\'om tumani' },
      { id: 37, nomi: 'Paxtachi tumani' },
      { id: 38, nomi: 'Payariq tumani' },
      { id: 39, nomi: 'Qo\'shrabot tumani' },
      { id: 40, nomi: 'Toyloq tumani' },
      { id: 41, nomi: 'Urgut tumani' },
    ],
  },
  {
    id: 4, nomi: 'Andijon viloyati',
    hududlar: [
      { id: 42, nomi: 'Andijon shahri' },
      { id: 43, nomi: 'Asaka tumani' },
      { id: 44, nomi: 'Baliqchi tumani' },
      { id: 45, nomi: 'Bo\'z tumani' },
      { id: 46, nomi: 'Buloqboshi tumani' },
      { id: 47, nomi: 'Jalaquduq tumani' },
      { id: 48, nomi: 'Izboskan tumani' },
      { id: 49, nomi: 'Marhamat tumani' },
      { id: 50, nomi: 'Oltinkul tumani' },
      { id: 51, nomi: 'Pakhtaobod tumani' },
      { id: 52, nomi: 'Qo\'rg\'ontepa tumani' },
      { id: 53, nomi: 'Shahrixon tumani' },
      { id: 54, nomi: 'Ulugnor tumani' },
      { id: 55, nomi: 'Xo\'jaobod tumani' },
    ],
  },
  {
    id: 5, nomi: 'Farg\'ona viloyati',
    hududlar: [
      { id: 56, nomi: 'Farg\'ona shahri' },
      { id: 57, nomi: 'Bag\'dod tumani' },
      { id: 58, nomi: 'Beshariq tumani' },
      { id: 59, nomi: 'Buvayda tumani' },
      { id: 60, nomi: 'Dang\'ara tumani' },
      { id: 61, nomi: 'Furqat tumani' },
      { id: 62, nomi: 'Qo\'qon shahri' },
      { id: 63, nomi: 'Marg\'ilon shahri' },
      { id: 64, nomi: 'Oltiariq tumani' },
      { id: 65, nomi: 'O\'zbekiston tumani' },
      { id: 66, nomi: 'Quva tumani' },
      { id: 67, nomi: 'Rishton tumani' },
      { id: 68, nomi: 'So\'x tumani' },
      { id: 69, nomi: 'Toshloq tumani' },
      { id: 70, nomi: 'Uchko\'prik tumani' },
      { id: 71, nomi: 'Yozyovon tumani' },
    ],
  },
  {
    id: 6, nomi: 'Namangan viloyati',
    hududlar: [
      { id: 72, nomi: 'Namangan shahri' },
      { id: 73, nomi: 'Chortoq tumani' },
      { id: 74, nomi: 'Chust tumani' },
      { id: 75, nomi: 'Kosonsoy tumani' },
      { id: 76, nomi: 'Mingbuloq tumani' },
      { id: 77, nomi: 'Namangan tumani' },
      { id: 78, nomi: 'Norin tumani' },
      { id: 79, nomi: 'Pop tumani' },
      { id: 80, nomi: 'To\'raqo\'rg\'on tumani' },
      { id: 81, nomi: 'Uchqo\'rg\'on tumani' },
      { id: 82, nomi: 'Yangiqo\'rg\'on tumani' },
    ],
  },
  {
    id: 7, nomi: 'Buxoro viloyati',
    hududlar: [
      { id: 83, nomi: 'Buxoro shahri' },
      { id: 84, nomi: 'Alat tumani' },
      { id: 85, nomi: 'Buxoro tumani' },
      { id: 86, nomi: 'G\'ijduvon tumani' },
      { id: 87, nomi: 'Jondor tumani' },
      { id: 88, nomi: 'Kogon shahri' },
      { id: 89, nomi: 'Peshku tumani' },
      { id: 90, nomi: 'Qorako\'l tumani' },
      { id: 91, nomi: 'Qorovulbozor tumani' },
      { id: 92, nomi: 'Romitan tumani' },
      { id: 93, nomi: 'Shofirkon tumani' },
      { id: 94, nomi: 'Vobkent tumani' },
    ],
  },
  {
    id: 8, nomi: 'Qashqadaryo viloyati',
    hududlar: [
      { id: 95,  nomi: 'Qarshi shahri' },
      { id: 96,  nomi: 'Chiroqchi tumani' },
      { id: 97,  nomi: 'Dehqonobod tumani' },
      { id: 98,  nomi: 'G\'uzor tumani' },
      { id: 99,  nomi: 'Kamashi tumani' },
      { id: 100, nomi: 'Kasbi tumani' },
      { id: 101, nomi: 'Kitob tumani' },
      { id: 102, nomi: 'Koson tumani' },
      { id: 103, nomi: 'Mirishkor tumani' },
      { id: 104, nomi: 'Muborak tumani' },
      { id: 105, nomi: 'Nishon tumani' },
      { id: 106, nomi: 'Shahrisabz tumani' },
      { id: 107, nomi: 'Yakkabog\' tumani' },
    ],
  },
  {
    id: 9, nomi: 'Surxondaryo viloyati',
    hududlar: [
      { id: 108, nomi: 'Termiz shahri' },
      { id: 109, nomi: 'Angor tumani' },
      { id: 110, nomi: 'Bandixon tumani' },
      { id: 111, nomi: 'Boysun tumani' },
      { id: 112, nomi: 'Denov tumani' },
      { id: 113, nomi: 'Jarqo\'rg\'on tumani' },
      { id: 114, nomi: 'Muzrabot tumani' },
      { id: 115, nomi: 'Oltinsoy tumani' },
      { id: 116, nomi: 'Qiziriq tumani' },
      { id: 117, nomi: 'Qumqo\'rg\'on tumani' },
      { id: 118, nomi: 'Sariosiyo tumani' },
      { id: 119, nomi: 'Sherobod tumani' },
      { id: 120, nomi: 'Shurchi tumani' },
      { id: 121, nomi: 'Uzun tumani' },
    ],
  },
  {
    id: 10, nomi: 'Navoiy viloyati',
    hududlar: [
      { id: 122, nomi: 'Navoiy shahri' },
      { id: 123, nomi: 'Karmana tumani' },
      { id: 124, nomi: 'Konimex tumani' },
      { id: 125, nomi: 'Navbahor tumani' },
      { id: 126, nomi: 'Nurota tumani' },
      { id: 127, nomi: 'Qiziltepa tumani' },
      { id: 128, nomi: 'Tomdi tumani' },
      { id: 129, nomi: 'Uchquduq tumani' },
      { id: 130, nomi: 'Xatirchi tumani' },
      { id: 131, nomi: 'Zarafshon shahri' },
    ],
  },
  {
    id: 11, nomi: 'Jizzax viloyati',
    hududlar: [
      { id: 132, nomi: 'Jizzax shahri' },
      { id: 133, nomi: 'Arnasoy tumani' },
      { id: 134, nomi: 'Baxmal tumani' },
      { id: 135, nomi: 'Do\'stlik tumani' },
      { id: 136, nomi: 'Forish tumani' },
      { id: 137, nomi: 'G\'allaorol tumani' },
      { id: 138, nomi: 'Mirzacho\'l tumani' },
      { id: 139, nomi: 'Paxtakor tumani' },
      { id: 140, nomi: 'Yangiobod tumani' },
      { id: 141, nomi: 'Zomin tumani' },
      { id: 142, nomi: 'Zarbdor tumani' },
      { id: 143, nomi: 'Zafarobod tumani' },
      { id: 144, nomi: 'Sharof Rashidov tumani' },
    ],
  },
  {
    id: 12, nomi: 'Sirdaryo viloyati',
    hududlar: [
      { id: 145, nomi: 'Guliston shahri' },
      { id: 146, nomi: 'Boyovut tumani' },
      { id: 147, nomi: 'Guliston tumani' },
      { id: 148, nomi: 'Xovos tumani' },
      { id: 149, nomi: 'Mirzaobod tumani' },
      { id: 150, nomi: 'Oqoltin tumani' },
      { id: 151, nomi: 'Sardoba tumani' },
      { id: 152, nomi: 'Sayxunobod tumani' },
      { id: 153, nomi: 'Shirin shahri' },
    ],
  },
  {
    id: 13, nomi: 'Xorazm viloyati',
    hududlar: [
      { id: 154, nomi: 'Urganch shahri' },
      { id: 155, nomi: 'Bog\'ot tumani' },
      { id: 156, nomi: 'Gurlan tumani' },
      { id: 157, nomi: 'Xiva tumani' },
      { id: 158, nomi: 'Xonqa tumani' },
      { id: 159, nomi: 'Qo\'shko\'pir tumani' },
      { id: 160, nomi: 'Shovot tumani' },
      { id: 161, nomi: 'Tuproqqal\'a tumani' },
      { id: 162, nomi: 'Urganch tumani' },
      { id: 163, nomi: 'Yangiariq tumani' },
      { id: 164, nomi: 'Yangibozor tumani' },
    ],
  },
  {
    id: 14, nomi: 'Qoraqalpog\'iston Respublikasi',
    hududlar: [
      { id: 165, nomi: 'Nukus shahri' },
      { id: 166, nomi: 'Amudaryo tumani' },
      { id: 167, nomi: 'Beruniy tumani' },
      { id: 168, nomi: 'Chimboy tumani' },
      { id: 169, nomi: 'Ellikkala tumani' },
      { id: 170, nomi: 'Kegeyli tumani' },
      { id: 171, nomi: 'Mo\'ynoq tumani' },
      { id: 172, nomi: 'Nukus tumani' },
      { id: 173, nomi: 'Qanliko\'l tumani' },
      { id: 174, nomi: 'Qo\'ng\'irot tumani' },
      { id: 175, nomi: 'Shumanay tumani' },
      { id: 176, nomi: 'Taxtako\'pir tumani' },
      { id: 177, nomi: 'To\'rtko\'l tumani' },
      { id: 178, nomi: 'Xo\'jayli tumani' },
    ],
  },
]

const viloyatlar = ref(VILOYATLAR)
const hududlar   = ref(VILOYATLAR.flatMap((v) =>
  v.hududlar.map((h) => ({ ...h, shahar: v.nomi, viloyat_id: v.id }))
))
const isLoading = ref(false)
const isLoaded  = ref(true)  // statik — har doim tayyor

export function useHududlar() {
  // fetchHududlar — eski interfeys bilan moslik uchun (hech narsa qilmaydi)
  async function fetchHududlar() {}

  return {
    viloyatlar: readonly(viloyatlar),
    hududlar:   readonly(hududlar),
    isLoading:  readonly(isLoading),
    isLoaded:   readonly(isLoaded),
    fetchHududlar,
  }
}
