// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 14.06.2026, 15:31:01
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["D:/Asosiy loyihalar/husma test2/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Asosiy loyihalar/husma test2/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Asosiy loyihalar/husma test2/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Asosiy loyihalar/husma test2/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Asosiy loyihalar/husma test2/app/plugins/**/*.{js,ts,mjs}","D:/Asosiy loyihalar/husma test2/app/composables/**/*.{js,ts,mjs}","D:/Asosiy loyihalar/husma test2/app/utils/**/*.{js,ts,mjs}","D:/Asosiy loyihalar/husma test2/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Asosiy loyihalar/husma test2/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","D:/Asosiy loyihalar/husma test2/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","D:/Asosiy loyihalar/husma test2/app/app.config.{js,ts,mjs}","D:/Asosiy loyihalar/husma test2/app/spa-loading-template.html"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;