// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 15/06/2026, 20:32:39
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/Laptop/Desktop/otkuriy/husmaTest/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Laptop/Desktop/otkuriy/husmaTest/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Laptop/Desktop/otkuriy/husmaTest/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Laptop/Desktop/otkuriy/husmaTest/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Laptop/Desktop/otkuriy/husmaTest/app/plugins/**/*.{js,ts,mjs}","C:/Users/Laptop/Desktop/otkuriy/husmaTest/app/composables/**/*.{js,ts,mjs}","C:/Users/Laptop/Desktop/otkuriy/husmaTest/app/utils/**/*.{js,ts,mjs}","C:/Users/Laptop/Desktop/otkuriy/husmaTest/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Laptop/Desktop/otkuriy/husmaTest/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Laptop/Desktop/otkuriy/husmaTest/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Laptop/Desktop/otkuriy/husmaTest/app/app.config.{js,ts,mjs}","C:/Users/Laptop/Desktop/otkuriy/husmaTest/app/spa-loading-template.html"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;